//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSA
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WSadaGCIT.com/", ConfigurationName="WSA.WSAdaptadorSoap")]
    public interface WSAdaptadorSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/ConsultarSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.ConsultarSaldoResponse ConsultarSaldo(WSA.ConsultarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/ConsultarSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.ConsultarSaldoResponse> ConsultarSaldoAsync(WSA.ConsultarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/ConsultarSaldoBono", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.ConsultarSaldoBonoResponse ConsultarSaldoBono(WSA.ConsultarSaldoBonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/ConsultarSaldoBono", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.ConsultarSaldoBonoResponse> ConsultarSaldoBonoAsync(WSA.ConsultarSaldoBonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/GenerarTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.GenerarTicketResponse GenerarTicket(WSA.GenerarTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/GenerarTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.GenerarTicketResponse> GenerarTicketAsync(WSA.GenerarTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/RegistrarMonto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.RegistrarMontoResponse RegistrarMonto(WSA.RegistrarMontoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/RegistrarMonto", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.RegistrarMontoResponse> RegistrarMontoAsync(WSA.RegistrarMontoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/RegistrarMontoDescrip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.RegistrarMontoDescripResponse RegistrarMontoDescrip(WSA.RegistrarMontoDescripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/RegistrarMontoDescrip", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.RegistrarMontoDescripResponse> RegistrarMontoDescripAsync(WSA.RegistrarMontoDescripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/RegistrarMontoDesWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.RegistrarMontoDesWebResponse RegistrarMontoDesWeb(WSA.RegistrarMontoDesWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/RegistrarMontoDesWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.RegistrarMontoDesWebResponse> RegistrarMontoDesWebAsync(WSA.RegistrarMontoDesWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/Verificarlogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSA.VerificarloginResponse Verificarlogin(WSA.VerificarloginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSadaGCIT.com/Verificarlogin", ReplyAction="*")]
        System.Threading.Tasks.Task<WSA.VerificarloginResponse> VerificarloginAsync(WSA.VerificarloginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSaldo", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class ConsultarSaldoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public string usuario;
        
        public ConsultarSaldoRequest()
        {
        }
        
        public ConsultarSaldoRequest(string clave, string Clavecliente, string usuario)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSaldoResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class ConsultarSaldoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string ConsultarSaldoResult;
        
        public ConsultarSaldoResponse()
        {
        }
        
        public ConsultarSaldoResponse(string ConsultarSaldoResult)
        {
            this.ConsultarSaldoResult = ConsultarSaldoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSaldoBono", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class ConsultarSaldoBonoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public string usuario;
        
        public ConsultarSaldoBonoRequest()
        {
        }
        
        public ConsultarSaldoBonoRequest(string clave, string Clavecliente, string usuario)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSaldoBonoResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class ConsultarSaldoBonoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string ConsultarSaldoBonoResult;
        
        public ConsultarSaldoBonoResponse()
        {
        }
        
        public ConsultarSaldoBonoResponse(string ConsultarSaldoBonoResult)
        {
            this.ConsultarSaldoBonoResult = ConsultarSaldoBonoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarTicket", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class GenerarTicketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=3)]
        public decimal monto;
        
        public GenerarTicketRequest()
        {
        }
        
        public GenerarTicketRequest(string clave, string Clavecliente, string usuario, decimal monto)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.usuario = usuario;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarTicketResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class GenerarTicketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string GenerarTicketResult;
        
        public GenerarTicketResponse()
        {
        }
        
        public GenerarTicketResponse(string GenerarTicketResult)
        {
            this.GenerarTicketResult = GenerarTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarMonto", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class RegistrarMontoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public int tipoTransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=3)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=4)]
        public string monto;
        
        public RegistrarMontoRequest()
        {
        }
        
        public RegistrarMontoRequest(string clave, string Clavecliente, int tipoTransaccion, string usuario, string monto)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.tipoTransaccion = tipoTransaccion;
            this.usuario = usuario;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarMontoResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class RegistrarMontoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string RegistrarMontoResult;
        
        public RegistrarMontoResponse()
        {
        }
        
        public RegistrarMontoResponse(string RegistrarMontoResult)
        {
            this.RegistrarMontoResult = RegistrarMontoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarMontoDescrip", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class RegistrarMontoDescripRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public int tipoTransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=3)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=4)]
        public string monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=5)]
        public string descripcion;
        
        public RegistrarMontoDescripRequest()
        {
        }
        
        public RegistrarMontoDescripRequest(string clave, string Clavecliente, int tipoTransaccion, string usuario, string monto, string descripcion)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.tipoTransaccion = tipoTransaccion;
            this.usuario = usuario;
            this.monto = monto;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarMontoDescripResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class RegistrarMontoDescripResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string RegistrarMontoDescripResult;
        
        public RegistrarMontoDescripResponse()
        {
        }
        
        public RegistrarMontoDescripResponse(string RegistrarMontoDescripResult)
        {
            this.RegistrarMontoDescripResult = RegistrarMontoDescripResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarMontoDesWeb", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class RegistrarMontoDesWebRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public int tipoTransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=3)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=4)]
        public string monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=5)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=6)]
        public int idusuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=7)]
        public int idcliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=8)]
        public int operacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=9)]
        public string tipoap;
        
        public RegistrarMontoDesWebRequest()
        {
        }
        
        public RegistrarMontoDesWebRequest(string clave, string Clavecliente, int tipoTransaccion, string usuario, string monto, string descripcion, int idusuario, int idcliente, int operacion, string tipoap)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.tipoTransaccion = tipoTransaccion;
            this.usuario = usuario;
            this.monto = monto;
            this.descripcion = descripcion;
            this.idusuario = idusuario;
            this.idcliente = idcliente;
            this.operacion = operacion;
            this.tipoap = tipoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarMontoDesWebResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class RegistrarMontoDesWebResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string RegistrarMontoDesWebResult;
        
        public RegistrarMontoDesWebResponse()
        {
        }
        
        public RegistrarMontoDesWebResponse(string RegistrarMontoDesWebResult)
        {
            this.RegistrarMontoDesWebResult = RegistrarMontoDesWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Verificarlogin", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class VerificarloginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=1)]
        public string Clavecliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=2)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=3)]
        public string Claveusuario;
        
        public VerificarloginRequest()
        {
        }
        
        public VerificarloginRequest(string clave, string Clavecliente, string usuario, string Claveusuario)
        {
            this.clave = clave;
            this.Clavecliente = Clavecliente;
            this.usuario = usuario;
            this.Claveusuario = Claveusuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarloginResponse", WrapperNamespace="http://WSadaGCIT.com/", IsWrapped=true)]
    public partial class VerificarloginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSadaGCIT.com/", Order=0)]
        public string VerificarloginResult;
        
        public VerificarloginResponse()
        {
        }
        
        public VerificarloginResponse(string VerificarloginResult)
        {
            this.VerificarloginResult = VerificarloginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WSAdaptadorSoapChannel : WSA.WSAdaptadorSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WSAdaptadorSoapClient : System.ServiceModel.ClientBase<WSA.WSAdaptadorSoap>, WSA.WSAdaptadorSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSAdaptadorSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSAdaptadorSoapClient.GetBindingForEndpoint(endpointConfiguration), WSAdaptadorSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSAdaptadorSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSAdaptadorSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSAdaptadorSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSAdaptadorSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSAdaptadorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WSA.ConsultarSaldoResponse ConsultarSaldo(WSA.ConsultarSaldoRequest request)
        {
            return base.Channel.ConsultarSaldo(request);
        }
        
        public System.Threading.Tasks.Task<WSA.ConsultarSaldoResponse> ConsultarSaldoAsync(WSA.ConsultarSaldoRequest request)
        {
            return base.Channel.ConsultarSaldoAsync(request);
        }
        
        public WSA.ConsultarSaldoBonoResponse ConsultarSaldoBono(WSA.ConsultarSaldoBonoRequest request)
        {
            return base.Channel.ConsultarSaldoBono(request);
        }
        
        public System.Threading.Tasks.Task<WSA.ConsultarSaldoBonoResponse> ConsultarSaldoBonoAsync(WSA.ConsultarSaldoBonoRequest request)
        {
            return base.Channel.ConsultarSaldoBonoAsync(request);
        }
        
        public WSA.GenerarTicketResponse GenerarTicket(WSA.GenerarTicketRequest request)
        {
            return base.Channel.GenerarTicket(request);
        }
        
        public System.Threading.Tasks.Task<WSA.GenerarTicketResponse> GenerarTicketAsync(WSA.GenerarTicketRequest request)
        {
            return base.Channel.GenerarTicketAsync(request);
        }
        
        public WSA.RegistrarMontoResponse RegistrarMonto(WSA.RegistrarMontoRequest request)
        {
            return base.Channel.RegistrarMonto(request);
        }
        
        public System.Threading.Tasks.Task<WSA.RegistrarMontoResponse> RegistrarMontoAsync(WSA.RegistrarMontoRequest request)
        {
            return base.Channel.RegistrarMontoAsync(request);
        }
        
        public WSA.RegistrarMontoDescripResponse RegistrarMontoDescrip(WSA.RegistrarMontoDescripRequest request)
        {
            return base.Channel.RegistrarMontoDescrip(request);
        }
        
        public System.Threading.Tasks.Task<WSA.RegistrarMontoDescripResponse> RegistrarMontoDescripAsync(WSA.RegistrarMontoDescripRequest request)
        {
            return base.Channel.RegistrarMontoDescripAsync(request);
        }
        
        public WSA.RegistrarMontoDesWebResponse RegistrarMontoDesWeb(WSA.RegistrarMontoDesWebRequest request)
        {
            return base.Channel.RegistrarMontoDesWeb(request);
        }
        
        public System.Threading.Tasks.Task<WSA.RegistrarMontoDesWebResponse> RegistrarMontoDesWebAsync(WSA.RegistrarMontoDesWebRequest request)
        {
            return base.Channel.RegistrarMontoDesWebAsync(request);
        }
        
        public WSA.VerificarloginResponse Verificarlogin(WSA.VerificarloginRequest request)
        {
            return base.Channel.Verificarlogin(request);
        }
        
        public System.Threading.Tasks.Task<WSA.VerificarloginResponse> VerificarloginAsync(WSA.VerificarloginRequest request)
        {
            return base.Channel.VerificarloginAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSAdaptadorSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSAdaptadorSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSAdaptadorSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ca01-vm03.sagcit.com/wsadaptadorgcit/WsAdaMain.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSAdaptadorSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ca01-vm03.sagcit.com/wsadaptadorgcit/WsAdaMain.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSAdaptadorSoap,
            
            WSAdaptadorSoap12,
        }
    }
}
